[build-system]
requires = ["setuptools>=45", "setuptools-git-versioning[toml]>=0.10.2"]
build-backend = "setuptools.build_meta"

[project]
name = "first_py_package"
dynamic = ["version"]

[tool.setuptools-git-versioning]
enabled = true
write_to = "first_py_package/_version.py"