[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "first_py_package"
version = "0.0.1"
dependencies = [
    'importlib-metadata; python_version<"3.8"'
]

