# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '5.0.1.dev0+g88b552a.d20230403'
__version_tuple__ = version_tuple = (5, 0, 1, 'dev0', 'g88b552a.d20230403')
