# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '3.2.dev0+g60f0038.d20230403'
__version_tuple__ = version_tuple = (3, 2, 'dev0', 'g60f0038.d20230403')
